version: '3.0'

services:
  autocomplete_restapi:
    image: autocomplete_restapi
    restart: always
    ports:
      - "6606:6606"
  
  autocomplete_restapi_test:
    image: autocomplete_restapi
    command: ["python", "/autocomplete_restapi/src/test_cases.py"]